spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.31.7:49154/web_db?characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: webdb
    password: p@ssword123
    driver-class-name: com.mysql.cj.jdbc.Driver
